/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorajorge;

import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author emanuelm
 */
public class Calculadora extends JFrame {
    
    boolean entrandoNum1;
    int numero1, numero2, resultado;
    String operacion;
    double resultDificil;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        entrandoNum1 = true;
        operacion = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new JMenuItem();
        num1 = new JButton();
        num2 = new JButton();
        num33 = new JButton();
        operMas = new JButton();
        num5 = new JButton();
        jButton6 = new JButton();
        num4 = new JButton();
        operMenos = new JButton();
        jButton9 = new JButton();
        jButton10 = new JButton();
        jButton11 = new JButton();
        jButton12 = new JButton();
        jButton15 = new JButton();
        operIgual = new JButton();
        resultadoMostrar = new JLabel();
        operRaiz = new JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        num1.setText("1");
        num1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                num1MouseClicked(evt);
            }
        });
        num1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setText("2");
        num2.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                num2MouseClicked(evt);
            }
        });

        num33.setText("3");

        operMas.setText("+");
        operMas.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                operMasMouseClicked(evt);
            }
        });

        num5.setText("5");

        jButton6.setText("6");

        num4.setText("4");

        operMenos.setText("-");
        operMenos.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                operMenosMouseClicked(evt);
            }
        });

        jButton9.setText("8");

        jButton10.setText("9");

        jButton11.setText("7");

        jButton12.setText("x");

        jButton15.setText("0");

        operIgual.setText("=");
        operIgual.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                operIgualMouseClicked(evt);
            }
        });
        operIgual.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                operIgualActionPerformed(evt);
            }
        });

        operRaiz.setText("=");
        operRaiz.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                operRaizMouseClicked(evt);
            }
        });
        operRaiz.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                operRaizActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(resultadoMostrar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num4)
                        .addGap(18, 18, 18)
                        .addComponent(num5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(operMenos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num1)
                        .addGap(18, 18, 18)
                        .addComponent(num2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(num33)
                        .addGap(18, 18, 18)
                        .addComponent(operMas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton15)
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(operRaiz)
                            .addComponent(operIgual))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(resultadoMostrar, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(num1)
                    .addComponent(num2)
                    .addComponent(num33)
                    .addComponent(operMas))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(num4)
                    .addComponent(num5)
                    .addComponent(jButton6)
                    .addComponent(operMenos))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton12))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(operIgual))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operRaiz)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1MouseClicked(MouseEvent evt) {//GEN-FIRST:event_num1MouseClicked
        // TODO add your handling code here:
        resultadoMostrar.setText(resultadoMostrar.getText() + num1.getText());
        if (entrandoNum1) {
            if (numero1 == 0) {
                numero1 = Integer.parseInt(num1.getText());
            } else {
                numero1 = numero1 * 10 + Integer.parseInt(num1.getText());
            }
        } else {
            if (numero2 == 0) {
                numero2 = Integer.parseInt(num1.getText());
            } else {
                numero2 = numero2 * 10 + Integer.parseInt(num1.getText());
            }
        }
        
        System.out.println(numero1);
    }//GEN-LAST:event_num1MouseClicked
    
    private void operIgualActionPerformed(ActionEvent evt) {//GEN-FIRST:event_operIgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operIgualActionPerformed
    
    private void num1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed
    
    private void num2MouseClicked(MouseEvent evt) {//GEN-FIRST:event_num2MouseClicked
        // TODO add your handling code here:
        resultadoMostrar.setText(resultadoMostrar.getText() + num2.getText());
        if (entrandoNum1) {
            if (numero1 == 0) {
                numero1 = Integer.parseInt(num2.getText());
            } else {
                numero1 = numero1 * 10 + Integer.parseInt(num2.getText());
            }
        } else {
            if (numero2 == 0) {
                numero2 = Integer.parseInt(num2.getText());
            } else {
                numero2 = numero2 * 10 + Integer.parseInt(num2.getText());
            }
        }
    }//GEN-LAST:event_num2MouseClicked
    
    private void operIgualMouseClicked(MouseEvent evt) {//GEN-FIRST:event_operIgualMouseClicked
        // TODO add your handling code here:
        resultadoMostrar.setText(resultadoMostrar.getText() + operIgual.getText());
        if (operacion.equals("suma")) {
            resultado = numero1 + numero2;
        }else if(operacion.equals("resta")){
            resultado = numero1 - numero2;
        }
        resultadoMostrar.setText(resultadoMostrar.getText() + " " + resultado);
        
    }//GEN-LAST:event_operIgualMouseClicked
    
    private void operMasMouseClicked(MouseEvent evt) {//GEN-FIRST:event_operMasMouseClicked
        // TODO add your handling code here:
        entrandoNum1 = false;
        resultadoMostrar.setText(resultadoMostrar.getText() + operMas.getText());
        operacion = "suma";
    }//GEN-LAST:event_operMasMouseClicked
    
    private void operMenosMouseClicked(MouseEvent evt) {//GEN-FIRST:event_operMenosMouseClicked
        // TODO add your handling code here:
        entrandoNum1 = false;
        resultadoMostrar.setText(resultadoMostrar.getText() + operMenos.getText());
        operacion = "resta";
    }//GEN-LAST:event_operMenosMouseClicked

    private void operRaizMouseClicked(MouseEvent evt) {//GEN-FIRST:event_operRaizMouseClicked
        // TODO add your handling code here:
        resultDificil = Math.sqrt(numero1);
        System.out.println(resultDificil);
    }//GEN-LAST:event_operRaizMouseClicked

    private void operRaizActionPerformed(ActionEvent evt) {//GEN-FIRST:event_operRaizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operRaizActionPerformed
    
    private void num3MouseClicked(MouseEvent evt) {
        // TODO add your handling code here:
        resultadoMostrar.setText(resultadoMostrar.getText() + num33);
    }
    
    private void num4MouseClicked(MouseEvent evt) {
        // TODO add your handling code here:
        resultadoMostrar.setText(num4.getText());
    }
    
    private void num5MouseClicked(MouseEvent evt) {
        // TODO add your handling code here:
        resultadoMostrar.setText(num5.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton10;
    private JButton jButton11;
    private JButton jButton12;
    private JButton jButton15;
    private JButton jButton6;
    private JButton jButton9;
    private JMenuItem jMenuItem1;
    private JButton num1;
    private JButton num2;
    private JButton num33;
    private JButton num4;
    private JButton num5;
    private JButton operIgual;
    private JButton operMas;
    private JButton operMenos;
    private JButton operRaiz;
    private JLabel resultadoMostrar;
    // End of variables declaration//GEN-END:variables
}
